name: dev workflow

on:
    workflow_dispatch
#  push:
#    paths-ignore:
#      - '.github/workflows/gradle.yml'
#      - 'README.md'
#  schedule:
#   - cron: '*/5 * * * *'



jobs:
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}

  job1:
    name: Job1
    runs-on: ubuntu-20.04
    timeout-minutes: 1
   
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    
    - name: sleep
      run: |
          sleep 90
  
  job2:
    name: Job2
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    needs: job1
#    if: ${{ needs.job1.result == 'failure' }}
    
    steps:
    - name: Notification
      run: |
        echo "${{ needs.job1.result }}"
