name: dev workflow

on:
#    workflow_dispatch
#  push:
#    paths-ignore:
#      - '.github/workflows/gradle.yml'
#      - 'README.md'
#  schedule:
#   - cron: '*/5 * * * *'
  

  push:
    branches: [ dev ]


jobs:
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}

  job1:
    name: Job1
    runs-on: ubuntu-20.04
    timeout-minutes: 1
   
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    
    - name: sleep
      run: |
          sleep 120
          
    - name: echo job status
      if: always()
      run: |
        echo "${{ job.job1.status }}"
