name: dev workflow

on:
#  push:
#    paths:
#        - '.github/workflows/dev.yml'
#    paths-ignore:
#      - '.github/workflows/gradle.yml'
#      - 'README.md'
  schedule:
  - cron: '*/5 * * * *'

jobs:
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}

  job1:
    name: Job1
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    outputs:
      STATUS: ${{ steps.final-status.outputs.status }}
    steps:
    
    - name: Get public IP
      run: |
         echo "RUNNER_PUBLIC_IP=$(curl https://ipinfo.io/ip)" >> $GITHUB_ENV
         
    - name: Log public IP of runner
      run: |
        echo ${{ env.RUNNER_PUBLIC_IP }}
        
    - name: updatemanifest
      id: update-manifest
      run: |
        echo "this is update manifest"
      continue-on-error: true
      
    - name: repush manifest
      id: repush-manifest
      run: |
        variable="abcd"
        echo $variable
        echo "this is repush manifest"
   
    - name: Deploy
      id: deployment
      run: |
        echo "this is deploy step"
    
    - name: Status
      if: ${{ always() && steps.deployment.outcome != 'success' && steps.update-manifest.outcome == 'success' || steps.repush-manifest.outcome == 'success' && job.status != 'cancelled' }}
      run: |
          echo "this is status step"
          echo $GITHUB_ACTOR
          
#    - name: Status
#      id: final-status
#      if: always()
#      run: |
#        echo "::set-output name=status::${{ job.status }}"
#        echo "JOB STATUS= ${{ job.status }}"
        
#    - name: Cancelled notification
#      if: ${{ cancelled() }}
#      run: |
#        echo "Workflow Cancelled"
  
