name: dev workflow

on:
  push:
    paths:
        - '.github/workflows/dev.yml'
#    paths-ignore:
#      - '.github/workflows/gradle.yml'
#      - 'README.md'
#  schedule:
#   - cron: '*/5 * * * *'

jobs:
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}

  job1:
    name: Job1
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    outputs:
      STATUS: ${{ steps.final-status.outputs.status }}
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    
    - name: sleep
      run: |
          sleep 90
          
    - name: Status
      id: final-status
      if: always()
      run: |
        echo "::set-output name=status::${{ job.status }}"
        echo "JOB STATUS= ${{ job.status }}"
  
    - name: Cancelled notification
      if: ${{ cancelled() }}
      run: |
        echo "Workflow Cancelled"
  
  job2:
    name: Job2
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    needs: job1
    if: always()
#    if: ${{ always() && needs.job1.result == 'failure' }}
    
    steps:
    - name: Notification
      run: |
        echo "needs result= ${{needs.job1.result}}"
        echo "${{needs.job1.outputs.STATUS}}"
