name: master workflow

on:
#    workflow_dispatch
#  push:
#    paths-ignore:
#      - '.github/workflows/gradle.yml'
#      - 'README.md'
#  schedule:
#   - cron: '*/5 * * * *'
  

  push:
    branches: [ master ]


jobs:
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}

  job1:
    name: Job1
    runs-on: ubuntu-20.04
    environment: STG
 #   env:
#      VARIABLE: CidrBlock
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
       ref: master
   
    - name: Display file
      run: |
        cat $GITHUB_WORKSPACE/.github/workspace/dev.yml
