# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      VARIABLE: xyz
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
    - name: Configure AWS credentials from Actions account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: us-west-2
    ##- name: Copy Github Action from the core rep with the AWS CLI
      ##run: |
        ##ls -al ~/
       ## aws s3 sync s3://maven-repo-firecracker-test/releases/ ~/.m2/repository/
        ##ls -al ~/.m2
   # - name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
   # - name: Build with Gradle
   #   run: ./gradlew clean build
   # - name: Build Docker Image
    #  run: ./gradlew docker
    
      
    #- name: Login to Amazon ECR
     # id: login-ecr
      #uses: aws-actions/amazon-ecr-login@v1
      
    - name: Push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: gh-actions
        IMAGE_TAG: ${{ github.sha }}
        IMAGE_NAME: test-ghactions
      run: |
        VARIABLE=ABC
        echo $VARIABLE
        ls
        echo $ECR_REGISTRY
        docker image ls
      
    

    
