# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:

  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      id: checkout
      with:
       fetch-depth: 0
        
    - name: disply files
      run: ls -al
    
    - name: Get tag number
      id: tag-version
      run: |
         git describe
         echo "TAG_VERSION=$($GITHUB_WORKSPACE/.github/workflows/gitTags.sh)" >> $GITHUB_ENV
         
    - name: Log tag number
      run: |
         echo "git SHA is $GITHUB_SHA"
         echo "tag number is ${{ env.TAG_VERSION }}"
   
    - name: Create git Tag
      uses: negz/create-tag@v1
      with:
        version: ${{ env.TAG_VERSION }}
        message: version  ${{ env.TAG_VERSION }}
        #token: ${{ secrets.GITHUB_TOKEN }}
      
      
    

    
