name: master workflow

on:
#    workflow_dispatch
#  push:
#    paths-ignore:
#      - '.github/workflows/gradle.yml'
#      - 'README.md'
#  schedule:
#   - cron: '*/5 * * * *'
  
  push:
    branches: [ master ]


jobs:
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}
      
  job1:
    name: Job1
    runs-on: ubuntu-20.04
    environment: STG
 #   env:
#      VARIABLE: CidrBlock
      
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0 
   
    - name: Git SHA for slack notifications
      run: |
        echo "SHORT_SHA=`echo $GITHUB_SHA | cut -c1-8`" >> $GITHUB_ENV
        
    - name: Log git SHA
      run: |
        echo "Git SHA is ${{ env.SHORT_SHA }}"
       
    - name: Git checkout
      run: |
        echo "Tag before checkout=$(git describe --tags --abbrev=0)"
        git fetch --tags --force
        echo "Tag after checkout=$(git describe --tags --abbrev=0)"
        
    - name: Get tag number
      id: tag-version
      run: |
         chmod +x $GITHUB_WORKSPACE/.github/workflows/gitTags.sh
         echo "TAG_VERSION=0.1.1" >> $GITHUB_ENV
#         echo "TAG_VERSION=$($GITHUB_WORKSPACE/.github/workflows/gitTags.sh)" >> $GITHUB_ENV
         
    - name: Log tag number
      run: |
         echo "tag number is ${{ env.TAG_VERSION }}"   
  
    - name: Create tag
      id: create-git-tag
      run: |
        git config --local user.email "rishitha@gmail.com"
        git config --local user.name "rishitha"
        git tag -a ${{ env.TAG_VERSION }} -m 'tag for commit ${{ env.SHORT_SHA }}'
#        echo "::set-output name=TAG_VALUE::$(git tag -a ${{ env.TAG_VERSION }} -m 'tag for commit ${{ env.SHORT_SHA }}')"
      
    - name: Push tag
      run: |
        echo "${{ steps.create-git-tag.outputs.TAG_VALUE }}"
        git push origin ${{ env.TAG_VERSION }}
    
    - name: Validating Git tag
      if: always()
      run: echo "${{ steps.create-git-tag.outcome }}"
      
    - name: Dump steps context
      if: always()
      env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
      
    - name: Git checkout - if create tag fails
      if: ${{ always() && steps.create-git-tag.outcome == 'failure' }}
      run: |
        echo "Tag before checkout=$(git describe --tags --abbrev=0)"
        git fetch --tags --force
        echo "Tag after checkout=$(git describe --tags --abbrev=0)"
   
    - name: Get tag number - if create tag fails
      if: ${{ always() && steps.create-git-tag.outcome == 'failure' }}
      run: |
        chmod +x $GITHUB_WORKSPACE/.github/workflows/gitTags.sh
        echo "TAG_VERSION=$($GITHUB_WORKSPACE/.github/workflows/gitTags.sh)" >> $GITHUB_ENV
         
    - name: Log tag - if create tag fails
      if: ${{ always() && steps.create-git-tag.outcome == 'failure' }}
      run: |
        echo "tag number is ${{ env.TAG_VERSION }}" 
        
    - name: Create tag - if create tag fails
      id: retry-git-tag
      if: ${{ always() && steps.create-git-tag.outcome == 'failure' }}
      run: |
        git config --local user.email "rishitha@gmail.com"
        git config --local user.name "rishitha"
        git tag -a ${{ env.TAG_VERSION }} -m "tag for commit ${{ env.SHORT_SHA }}"
        
    - name: Push tag
      if: ${{ always() && steps.create-git-tag.outcome == 'failure' }}
      run: |
        git push origin ${{ env.TAG_VERSION }}

    - name: Push tag
      run: |
        echo "${{ steps.create-git-tag.outputs.TAG_VALUE }}"
#        git push origin ${{ env.TAG_VERSION }}

