# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  
#  workflow_dispatch
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      id: checkout
      with:
       fetch-depth: 0
        
    - name: disply files
      run: ls -al
    
    - name: Get tag number
      id: tag-version
      run: |
         git describe --tags --abbrev=0
         chmod 777 $GITHUB_WORKSPACE/.github/workflows/gitTags.sh
         $GITHUB_WORKSPACE/.github/workflows/gitTags.sh
         echo "TAG_VERSION=$($GITHUB_WORKSPACE/.github/workflows/gitTags.sh)" >> $GITHUB_ENV
         
    - name: Log tag number
      run: |
         echo "git SHA is $GITHUB_SHA"
         echo "tag number is $TAG_VERSION"
   
    - name: Create git Tag
      run: |
         git tag -a $TAG_VERSION -m "autogenerated tag"
         git push
#     uses: negz/create-tag@v1
 #     with:
 #       version: $TAG_VERSION
 #       message: version  $TAG_VERSION
 #       token: $GITHUB_TOKEN
      
      
    

    
