name: master workflow

on:
#    workflow_dispatch
#  push:
#    paths-ignore:
#      - '.github/workflows/gradle.yml'
#      - 'README.md'
#  schedule:
#   - cron: '*/5 * * * *'
  

  push:
    branches: [ master ]


jobs:
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}

  job1:
    name: Job1
    runs-on: ubuntu-20.04
    environment: STG
 #   env:
#      VARIABLE: CidrBlock
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0 
       
    - name: Git checkout
      run: |
        echo "Tag before checkout=$(git describe --tags --abbrev=0)"
        git fetch --tags --force
        echo "Tag after checkout=$(git describe --tags --abbrev=0)"
        
    - name: Get tag number
      id: tag-version
      run: |
         echo "TAG_VERSION=$($GITHUB_WORKSPACE/.github/workflows/gitTags.sh)" >> $GITHUB_ENV
         
    - name: Log tag number
      run: |
         echo "tag number is ${{ env.TAG_VERSION }}"   
