name: testing script

on:
    workflow_dispatch
#  push:
#    paths-ignore:
#      - '.github/workflows/gradle.yml'
#      - 'README.md'
#  schedule:
#   - cron: '*/5 * * * *'
  

#  push:
#    branches: [ master ]


jobs:
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}

  job1:
    name: Job1
    runs-on: ubuntu-20.04
    environment:
            name: build
 #   env:
#      VARIABLE: CidrBlock
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
       fetch-depth: 0

    - name: Code build
      id: code-build
      run: |
        featureFlags=""
        while read line
        do
          featureFlags="$featureFlags $line"
        done < ./.env-flags
        
        echo "Feature Flags is: $featureFlags"
  
        echo "Yarn install"
        CI=true NODE_ENV=dev npx yarn install
        
        echo "Yarn build"
        $featureFlags npx yarn build
        
        echo "Yarn test"
        npx yarn test --coverage --watchAll=false
        
