name: testing script

on:
  push:
    branches: [ master ]


jobs:
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}

  job1:
    name: Job1
    runs-on: ubuntu-20.04
 #   env:
#      VARIABLE: CidrBlock
    steps:
 #   - name: checkout Another repo
 #     uses: actions/checkout@v2
 #     with:
  #      repository: 'rishithareddypasnoor007/AWS'
#        ref: master
        
    - name: get repo name
      run: |
          echo "REPOSITORY=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV 
    #      REPOSITORY=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
    #      echo $REPOSITORY
          
          
          
    - name: print repo name
      run: |
        echo "env repo : ${{ env.REPOSITORY }}"
  job2:
    runs-on: ubuntu-20.04
#    needs: build
#    env:
#      VARIABLE: CidrBlock
    steps:
    - name: Job2
      id: job2step
      run: |
          echo "Job 2  JOB=$GITHUB_JOB"
          echo "Job 2  RUN_ID=$GITHUB_RUN_ID"
          echo "Job 2 RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "Job 2  ACTION=$GITHUB_ACTION"
          echo ${{ steps.job2step.outcome }}

  #    - name: Set status check for deployment
  #      if: ${{ steps.job2step.outcome != 'success' }} 
  #      uses: ouzi-dev/commit-status-updater@v1.1.0
  #      with:
  #        status: "failure"
  #        url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}?check_suite_focus=true"
  #        description: " Service start failed"
  #        name: "Deployment"
  #        


