name: testing script

on:
  push:
    branches: [ master ]


jobs:
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}

  build:
    runs-on: ubuntu-20.04
    env:
      VARIABLE: CidrBlock
    steps:
    - name: checkout Another repo
      uses: actions/checkout@v2
      with:
        repository: 'rishithareddypasnoor007/AWS'
        ref: master
        
    - name: editing a file
      run: |
          echo "Job 1  JOB  ${{ GITHUB_JOB }}"
          echo "Job 1 RUN_ID-  ${{ GITHUB_RUN_ID }}"
          echo "Job 1 RUN_NUMBER -  ${{ GITHUB_RUN_NUMBER }}"
  job2:
    runs-on: ubuntu-20.04
    needs: build
    env:
      VARIABLE: CidrBlock
    steps:
    - name: checkout Another repo
      run: |
        echo "Job 2 JOB-  ${{ GITHUB_JOB }}"
        echo "Job 2 RUN_ID-  ${{ GITHUB_RUN_ID }}"
        echo "Job 2 RUN_NUMBER -  ${{ GITHUB_RUN_NUMBER }}"
        
        
    
